[package]
name = "n64-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
n64-core = { path = "../n64-core" }
env_logger = "0.11"
log = "0.4"
pixels = "0.15"
winit = "0.30"
ratatui = "0.29"
crossterm = "0.28"
cpal = "0.15"
